### ISSUE TITLE
Incompatible with latest EC/Flow

### ISSUE THREAD

**Issue by rquintos** [electric-cloud/electriccommander#7]
I see the date on this is about 2 years ago.  My assumption is that this is too old to import into the current EC version of 5.4.  Attempted import reports the following.
```
-bash-4.1$ ectool import --file workflowTimer.export
ectool error [InvalidXml]: No schema version found in export file
```

**Comment by lrochette** [comment]
Let me see if I can generate a new version

**Comment by rquintos** [comment]
Looking in detail, I was able to find that my pull added some extra characters in the xml.  Cleaned those up and I'm actually able to import it in.
